export const loginConst={
    'LOGIN_REQUEST' :'LOGIN_REQUEST',
    'LOGIN_SUCCESS' :'LOGIN_SUCCESS',
    'LOGIN_FAILED' :'LOGIN_FAILED',
}
export const logoutConst={
    'LOGOUT_REQUEST' :'LOGOUT_REQUEST',
    'LOGOUT_SUCCESS' :'LOGOUT_SUCCESS',
    'LOGOUT_FAILED' :'LOGOUT_FAILED',
}

export const addAddressConst={
    'ADDRESSADD_REQUEST' :'ADDRESSADD_REQUEST',
    'ADDRESSADD_SUCCESS' :'ADDRESSADD_SUCCESS',
    'ADDRESSADD_FAILED' :'ADDRESSADD_FAILED',
}